### ISSUE TITLE
Add a better error message when a invalid class_uid is used

### ISSUE THREAD

**Issue by ffalor** [aws-samples/amazon-security-lake#19]
When loading the OSCF schema a FileNotFoundError is thrown due to the SCHEMA_CLASS returning nil. 

```
[?] : ocsf_schema_1.0.0-rc.2
 > ocsf_schema_1.0.0-rc.2

{'version': 'ocsf_schema_1.0.0-rc.2', 'path': '***'}

Validating Against Event Class:  (1000)...

Traceback (most recent call last):
  File "/amazon-security-lake/validate_1.0.0-rc.2/validate.py", line 259, in <module>
    main()
  File "/amazon-security-lake/validate_1.0.0-rc.2/validate.py", line 198, in main
    with open(str(path.parent).replace('\\', '/')
FileNotFoundError: [Errno 2] No such file or directory: '/amazon-security-lake/validate_1.0.0-rc.2/ocsf_schema_1.0.0-rc.2/.json'
```

**Comment by adplotzk** [comment]
Added support for error handling on invalid schemas.
